name: _
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"
workspace:
  - forui
  - forui_assets
  - forui_hooks
  - forui_internal_gen
  - samples

dev_dependencies:
  flint: ^2.13.0
  melos: ^7.3.0

melos:
  ide:
    intellij:
      enabled: false

  command:
    bootstrap:
      hooks:
        post: melos run generate
  scripts:
    generate:
      description: "Generate code for all packages."
      run: melos run build_runner && melos run l10n
    build_runner:
      description: "Run build_runner for all packages."
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build --delete-conflicting-outputs
