name: forui
description: Beautifully designed, minimalistic widgets for desktop & touch devices.
version: 0.10.0+1
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/forus-labs/forui/tree/main/forui
issue_tracker: https://github.com/forus-labs/forui/issues
topics:
  - components
  - design-system
  - shadcn-ui
  - widget

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"
resolution: workspace
workspace:
  - example

dependencies:
  args: ^2.7.0
  collection: ^1.18.0
  dart_style: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  forui_assets: ^0.10.0
  google_fonts: ^6.2.0
  intl: any
  meta: ^1.11.0
  sugar: ^4.0.0
  vector_math: ^2.1.4
  yaml: ^3.1.3

dev_dependencies:
  analyzer: ^7.4.0
  build_runner: ^2.4.0
  code_builder: ^4.10.1
  flint: ^2.8.1
  flutter_test:
    sdk: flutter
  forui_internal_gen:
  http: ^1.2.2
  leak_tracker_flutter_testing: any
  mockito: ^5.4.6
  path: ^1.9.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
