name: forui_samples
description: "Samples for the Forui website"
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0"
resolution: workspace

dependencies:
  auto_route: 11.1.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_web_plugins:
    sdk: flutter
  forui:
  intl: any
  sugar: ^4.0.0

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/avatar.png
    - assets/forus-labs.png
