name: forui_hooks
description: "Companion hooks for Forui, a set of beautifully designed, minimalistic widgets for desktop & touch devices."
version: 0.7.0
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/forus-labs/forui/tree/main/forui_hooks
issue_tracker: https://github.com/forus-labs/forui/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  forui: ^0.7.0

dev_dependencies:
  flint: ^2.8.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  forui:
    path: ../forui

flutter:

