name: forui_internal_gen
description: "Internal code generation tool for Forui."
publish_to: 'none'
version: 0.0.0
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/forus-labs/forui/tree/main/forui_internal_gen
issue_tracker: https://github.com/forus-labs/forui/issues

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"
resolution: workspace

dependencies:
  analyzer: ^8.0.0
  build: ^3.0.0
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_style: ^3.0.1
  meta: ^1.16.0
  source_gen: ^3.0.0

dev_dependencies:
  build_test: ^3.3.2
  flint: ^2.8.1
  forui: ^0.16.0
  source_gen_test: ^1.1.1
  test: ^1.26.2
