name: Showcase Presubmit

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/showcase_presubmit.yaml
      - showcase/**

jobs:
  prepare:
    if: github.actor != 'forus-labs-token-mint'
    name: Prepare PR for review
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: showcase

    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_MINT_APP_ID }}
          private_key: ${{ secrets.TOKEN_MINT_PRIVATE_KEY }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: subosito/flutter-action@v2.12.0
        with:
          cache: true

      - uses: dart-lang/setup-dart@v1.4

      - run: flutter pub get
      - run: flutter pub global activate import_sorter
      - run: flutter pub global run import_sorter:main
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: dart fix --apply

      - uses: EndBug/add-and-commit@v9
        with:
          add: '*'
          push: true